project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
    - "!IDEAS.md"

website:
  title: "Abigail Lewis"
  #site-url: https://abbylewis.github.io
  description: "Personal website for Abigail (Abby) Lewis, a postdoctoral researcher at the Smithsonian Environmental Research Center"
  open-graph: true
  twitter-card: true
  navbar:
    pinned: true
    right:
      - text: "Home"
        file: index.qmd
      #- text: "Research"
      #  file: research.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "Data publications"
        file: open_science.qmd
      - text: "Teaching and outreach"
        file: teaching.qmd
      - text: "CV"
        file: cv.qmd
      - icon: envelope
        href: "mailto:abigail.sl.lewis@gmail.com"
      - icon: github
        href: https://github.com/abbylewis
        target: _blank
format:
  html:
    includes:
      in_header: header.html
    theme:
      - simplex
      - styles.scss

execute:
  echo: false
  message: false

